import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import Reviews from "@/components/reviews";
import RelatedProducts from "@/components/related-products";
import ProductFeatures from "@/components/product-features";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {" "}
        <Navbar /> {children} <ProductFeatures /> <Reviews />{" "}
        <RelatedProducts />
      </body>
    </html>
  );
}
